/*---------------------------------------------------------- 
MASV: 18120397 - 18120399 - 18120423
HO TEN CAC THANH VIEN NHOM: 
	Nguyễn Đặng Hồng Huy
	Phạm Đức Huy
	Trịnh Tấn Khoa
LAB: 03 - NHOM 
NGAY: 28/04/2021
----------------------------------------------------------*/ 
USE [QLSVNhom];

CREATE TABLE SINHVIEN
(
	MASV		NVARCHAR(20)	NOT NULL,
	HOTEN		NVARCHAR(100)	NOT NULL, 
	NGAYSINH	DATETIME,
	DIACHI		NVARCHAR(200),
	MALOP		VARCHAR(20), 
	TENDN		NVARCHAR(100)	UNIQUE, 
	MATKHAU		VARBINARY(MAX)		NOT NULL,

	CONSTRAINT PK_SV PRIMARY KEY (MASV)
);


CREATE TABLE NHANVIEN
(
	MANV		VARCHAR(20)		NOT NULL,  
	HOTEN		NVARCHAR(100)	NOT NULL, 
	EMAIL		VARCHAR(20),
	LUONG		VARBINARY(MAX),
	TENDN		NVARCHAR(100)	NOT NULL UNIQUE, 
	MATKHAU		VARBINARY(MAX),
	PUBKEY		VARCHAR(20)		NOT NULL UNIQUE,

	CONSTRAINT PK_NV PRIMARY KEY (MANV)
);

CREATE TABLE LOP
(
	MALOP		VARCHAR(20)		NOT NULL,  
	TENLOP		NVARCHAR(100)	NOT NULL, 
	MANV		VARCHAR(20),

	CONSTRAINT PK_LO PRIMARY KEY (MALOP)
);

CREATE TABLE HOCPHAN
(
	MAHP		VARCHAR(20)		NOT NULL,
	TENHP		NVARCHAR(100)	NOT NULL,
	SOTC		INT,

	CONSTRAINT PK_HP PRIMARY KEY (MAHP)
);

CREATE TABLE BANGDIEM
(
	MASV		NVARCHAR(20)	NOT NULL,
	MAHP		VARCHAR(20)		NOT NULL,
	DIEMTHI		VARBINARY(MAX),

	CONSTRAINT PK_BD PRIMARY KEY (MASV, MAHP)
);

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SV_LO FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
ALTER TABLE LOP ADD CONSTRAINT FK_LO_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE BANGDIEM ADD CONSTRAINT FK_BD_SV FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);
ALTER TABLE BANGDIEM ADD CONSTRAINT FK_BD_HP FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP);
